name: GitHub Actions Demo
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM dependencies
        run: |
          npm install

      - name: Run backend tests
        run: |
          npm run test

  docker-image:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moodrt:latest

#      - name: Run and test docker image
#        uses: addnab/docker-run-action@v3
#        with:
#          image: moodrt:latest
#          id: moodrt-container
#          run: |
#            echo "Running the docker image" |
#            docker  |
#            curl http://127.0.0.1:3000
