name: GitHub Actions Demo
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM dependencies
        run: |
          npm install

      - name: Run backend tests
        run: |
          npm run test

  docker-image:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/moodrt:latest

      - name: Run test docker image
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/moodrt:latest
          id: moodrt-container
          run: |
            ls
#  app-tests:
#    runs-on: ubuntu-latest
#    needs:
#      - docker-image
#    container:
#      image: ${{ secrets.DOCKER_HUB_USERNAME }}/moodrt:latest
#      ports:
#        - 3000:3000
#        - 8080:8080
#    steps:
#      - name: Backend response
#        run: http://localhost:3000
#
#      - name: Fronted response
#        run: http://localhost:8080